### ISSUE TITLE
montepython input parameters

### ISSUE THREAD

**Issue by gaby7646** [miguelzuma/hi_class_public#11]
Hi! I'm trying to test gravity models using hi_class and montepython, but i'm not sure how to implement the smg parameters in the .param 
In my .param I added the lines:
`data.cosmo_arguments['gravity_model'] = 'galileon' `
`data.cosmo_arguments['gravity_submodel'] = 'cubic'`
And this is the error:
`Something went wrong when calling CLASS
/_o_\  Error in Class: Class did not read input parameter(s): gravity_model,
       gravity_submodel `

**Comment by miguelzuma** [comment]
Hi,
it seems that MontePython is not reading your parameters, which could be due to different reasons. Can you check the following?
- can you check that you are setting the right Omega_smg?
```
data.cosmo_arguments['Omega_Lambda'] = 0.
data.cosmo_arguments['Omega_fld'] = 0.
data.cosmo_arguments['Omega_smg'] = -1.
```
The code won't read the parameters if it things there is no smg
- can you check that you're calling the right version of class from python/montepython? the gravity_submodel feature was not present in older versions. If you are using an old version you can always call a cubic galileon using the following parameters:
```
data.cosmo_arguments['gravity_model'] = 'galileon'
#variance is zero, parameters not varied
data.parameters['parameters_smg__1'] = [2.9,None,   None, 0.,   1, 'cosmo'] 
data.parameters['parameters_smg__2'] = [0., None,None, 0.,   1, 'cosmo'] 
data.parameters['parameters_smg__3'] = [-1, None, None, 0.,  1, 'cosmo'] 
data.parameters['parameters_smg__4'] = [-0.14,None,None, 0., 1, 'cosmo']

#quartic and quintic: just set to non-zero, and vary xi, c3
data.parameters['parameters_smg__5'] = [0, None,None, 0, 1, 'cosmo'] 
data.parameters['parameters_smg__6'] = [0, None,None, 0., 1, 'cosmo'] 
data.parameters['parameters_smg__7'] = [0, None,None, 0., 1, 'cosmo'] 
```
I attached the .param files I used for [this paper](https://inspirehep.net/literature/1609059) in [this file](https://github.com/miguelzuma/hi_class_public/files/6477794/galileons_nu.zip) (keep in mind that it was Planck 2015 then)

**Comment by gaby7646** [comment]
Thanks a lot Miguel! I followed your .param to implement the cubic galileon model but the error persists.
`  Cosmological Module Error:
 /|\   Something went wrong when calling CLASS
/_o_\  Error in Class: Class did not read input parameter(s): gravity_model,
       hubble_continuity_tol_smg, hubble_cubic_discrim_tol_smg, parameters_smg,
       hubble_cubic_taylor_tol_smg  `
I attached  the .log output generated with the input I'm using.


[log_g3nu_param.txt](https://github.com/miguelzuma/hi_class_public/files/6516680/log_g3nu_param.txt)

**Comment by miguelzuma** [comment]
The param file looks good. Please remove or comment out the following parameters `hubble_continuity_tol_smg, hubble_cubic_discrim_tol_smg, hubble_cubic_taylor_tol_smg`. They belong to a private version of the code, which I used in the example ini file.

Still, MP is not reading `gravity_model or parameters_smg`, which are correct parameters in the public version. Can you try the following things:

1. have you tried to do `make clean; make` to make sure the python wrapper is compiled correctly and from the right hi_class source? here is more info on installing and trying out the python wrapper https://github.com/lesgourg/class_public/wiki/Installation
2.  run the model on python using classy (see http://miguelzuma.github.io/hi_class_public/#resources for some examples). If it doesn't work for the cubic galileon there, does it work for other models (e.g. propto_omega with an expansion history, see hi_class.ini)
3. make sure that your montepython config file points to the right installation of hiclass

I hope this helps

**Comment by gaby7646** [comment]
Thanks a lot Miguel for your complete answer. I think it was a problem with classy because I have another class versions.
I also had to clean manually classy from my user site-packages. [https://github.com/lesgourg/class_public/issues/152]
