### ISSUE TITLE
Problem installing hi_class in ubuntu

### ISSUE THREAD

**Issue by Student-112** [miguelzuma/hi_class_public#9]
I was trying to install hi_class in Ubuntu 18.04 with gcc 7.5.0. I can run the python scripts and everything works fine however when I try to run `./class explanatory.ini` I get the following:

`Reading input parameters
 -> matched budget equations by adjusting Omega_Lambda = 6.878622e-01

Error running input_init_from_arguments
=>input_init_from_arguments(L:179) :error in input_init(&fc, ppr, pba, pth, ppt, ptr, ppm, psp, pnl, ple, pop, errmsg);
=>input_init(L:459) :could not open param_output with name output/explanatory00_parameters.ini and mode "w"`

Any recommendations to fix the problem?

**Extra information:**
I don't get any problem with class.

**Comment by miguelzuma** [comment]
You need to create the directory where the output will be stored (class
can't create directories, only files)
